repo_url: https://github.com/FCTE-Qualidade-de-Software-1/2025-2_T01_ADELE-GOLDSTINE
repo_name: T01 Adele Goldstine

site_name: Adele Goldstine - Trabalho Final
theme:
  name: material

  palette:
    - scheme: default
      accent: indigo
      primary: blue
      toggle: 
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode

    - scheme: slate
      primary: blue
      accent: indigo
      toggle: 
        icon: material/toggle-switch
        name: Switch to light mode
  
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - admonition
  - pymdownx.details
  - pymdownx.superfences
plugins:
  - search
  - panzoom:
      full_screen: True
      key: "none"

nav:
  - Home: "index.md"
  - Fase 1 - Propósito da Avaliação:
    - Objeto de Estudo: "fase_1/objeto-estudo.md"
    - Contexto da Avaliação: "fase_1/contexto-avaliacao.md"
    - Modelo de Qualidade: "fase_1/modelo-qualidade.md"
    - Conclusão: "fase_1/conclusao.md"
  - Fase 2 - Especificação da Avaliação:
    - Abordagem GQM: "fase_2/introducao_gqm.md"
    - Medição 1 - Confiabilidade: "fase_2/gqm_confiabilidade.md"
    - Medição 2 - Manutenibilidade: "fase_2/gqm_manutenibilidade.md"
    - Medição 3 - Segurança: "fase_2/gqm_seguranca.md"
    - Análise Geral das Medições: "fase_2/analise_geral.md"
    - Conclusão: "fase_2/conclusao.md"
  - Fase 3 - Projetar a Avaliação:
    - Projetar Avaliação: "fase_3/projetar.md"
  - Fase 4 - Execução da Avaliação:
    - Introdução: "fase_4/introducao-avaliacao.md"
    - Avaliação da Confiabilidade: "fase_4/avaliacao-confiabilidade.md"
    - Avaliação da Manutenibilidade: "fase_4/avaliacao-manutenibilidade.md"
    - Avaliação da Segurança: "fase_4/avaliacao-seguranca.md" 
    - Conclusão: "fase_4/conclusao-avaliacao.md"
  - Contribuições:
    - Fase 1: "contribuicoes/fase-1.md"
    - Fase 2: "contribuicoes/fase-2.md"
    - Fase 3: "contribuicoes/fase-3.md"
    - Fase 4: "contribuicoes/fase-4.md"
